# defaults
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory

name: Cloudiator
description: A cross-cloud orchestration framework
url: https://cloudiator.github.io
#url: http://localhost:4000

favicon: images/favicon.png

collections:
  docs:
    output: true
  features:
    output: false
  components:
    output: true

markdown: kramdown
highlighter: rouge

exclude: [vendor, script]
