# defaults
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory

name: Cloudiator
description: A multi-tenant, cross-cloud orchestration framework.
url: https://cloudiator.github.io
# url: http://localhost:4000

favicon: /images/favicon.png
logo: /images/logo.png

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  docs:
    output: true
  components:
    output: true
  api:
    output: true

defaults:
  - scope:
      path: "_api/colosseum"
    values:
      api: "colosseum"

google_site_verification: 1_UKbWPLg8mXzsfaB0OSRpLVp2vqfJ3DNdGSisGQ4o8

markdown: kramdown
highlighter: rouge

exclude: [README.md, vendor, script]
